SwaranAdmin/SwaranAdmin_New/Models/PriceCalculation/SpecialOccasionViewModel.cs
using SwaranAdmin_New.CustomValidation;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace SwaranAdmin_New.Models.PriceCalculation
{
    public class SpecialOccasionViewModel
    {
        public long OccasionsId { get; set; }
        public long CustomerRateId { get; set; }
        [Required]
        public string RateFormula { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string FromDate { get; set; }
        [Required]
        public string ToDate { get; set; }
        public string Comments { get; set; }
        public string RateName { get; set; }
        [DisplayName("Surcharge *")]
        [Required]
        public decimal Surcharge { get; set; }
        //[SpecialOccationValidation(OccasionsIdProperty = "OccasionsId", CustomerRateIdProperty = "CustomerRateId")]
        public string OccasionDataRange { get; set; }
        [DisplayName("Is Enabled")]
        public bool IsEnabled { get; set; }
        [DisplayName("Is Deleted")]
        public bool IsDeleted { get; set; }

        //public bool IsAllPlot { get; set; }
        public int IsAllPlot { get; set; }

        //public int[] AriaPointId { get; set; }
        //public SpecialOccasionAreaPointDom[] AreaPointId { get; set; }
        //public SpecialOccasionAreaPointDom[] FixedPriceId { get; set; }             
        public long[] AreaPointId { get; set; }
        public long[] FixedPriceId { get; set; }
        //public List<SelectListItem> AriaPointIds { get; set; }

        [DisplayName("Dropoff Charge *")]
        [Required]
        public decimal DropOffCharge { get; set; }

        public string DropOffComments { get; set; } 
        public bool IsBothAreapointApplied { get; set; }
    }

    public class SpOccCustomerRateViewModel
    {
        public long RateId { get; set; }
        public string RateName { get; set; }

    } 
    public class AllSpecialOccationViewModel
    {
        public List<POIAddressViewModel> AllPoiAddress { get; set; }
        public List<POIAddressViewModel> SpecialOccAddress { get; set; }  
    }
    public   class POIAddressViewModel 
    {
        public long AriaPointId { get; set; }
        public string AreaGroup { get; set; }
        public string FullPostcodeWithoutSpace { get; set; }
        public string FullPostcode { get; set; }
        public string OuterPostcode { get; set; }
        public string InnerPostcode { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string SearchName { get; set; }
        public string AreaType { get; set; }
        public long AreaTypeId { get; set; }
        public decimal Lat { get; set; }
        public decimal Long { get; set; }
        public decimal LiveLat { get; set; }
        public decimal LiveLong { get; set; }
        public string Town { get; set; }
        public bool IsDisplay { get; set; }
        public bool IsUpdated { get; set; }
        public bool IsDeleted { get; set; }
        public string CreatedDate { get; set; }
        public string ModifiedDate { get; set; }
        public decimal PickupCharge { get; set; }
        public decimal DropoffCharge { get; set; }
        public int AddressId { get; set; }
        public bool IsDefault { get; set; }
    }

    public class SaveFixedPriceDom
    {
        public long FromAreaPointId { get; set; }
        public long ToAreaPointId { get; set; }
        public decimal BasicPrice { get; set; }
        public decimal Distance { get; set; }
        public decimal Duration { get; set; }
    }

    public class FixedPriceDistanceTimeCalculationDom
    {
        //public long FromAreaPointId { get; set; }
        public string FromCoordinates { get; set; }
        //public string FromLong { get; set; }
        public string FromFullAddress { get; set; }
        //public long ToAreaPointId { get; set; }
        public string ToCoordinates { get; set; }
        //public string ToLong { get; set; }
        public string ToFullAddress { get; set; }
        //public decimal BasicPrice { get; set; }
        //public decimal Distance { get; set; }
        //public decimal Duration { get; set; }
    }

    public class SpecialOccasionAreaPointDom
    {
        public long? FromAreaPointId { get; set; }
        public long? ToAreaPointId { get; set; }
        public long? FixedPriceId { get; set; }
    }

    public class SpecialOccasionFixedPriceDom
    {
        public long? FromAreaPointId { get; set; }
        public long? ToAreaPointId { get; set; }
        public long? FixedPriceId { get; set; }
    }

}

SwaranAdmin/SwaranAdmin_New/Controllers/PriceCalculationCol/SpecialOccasionController.cs
using SwaranAdmin_New.DataAccess.PriceCalculationDal;
using SwaranAdmin_New.Models.PriceCalculation;
using System.Collections.Generic;
using System.Web.Mvc;

namespace SwaranAdmin_New.Controllers.PriceCalculationCol
{
    [Authorize]
    public class SpecialOccasionController : Controller
    {
        private SpecialOccasionDal rexSpecialOccasion = SpecialOccasionDal.Instance;
        // GET: SpecialOccasion
        public ActionResult SpecialOccasionView()
        {

            return View();
        }

        public ActionResult AddSpecialOccasionView()
        {
            var model = new SpecialOccasionViewModel();
            model.IsAllPlot = 1;
            return View(model);
        }

        [HttpPost]
        public ActionResult AddSpecialOccasionView(SpecialOccasionViewModel model)
        {
            //model.IsAllPlot = model.AriaPointId == null ? true : model.IsAllPlot;
            //if (model.IsAllPlot)
            //{
            //    if (ModelState.ContainsKey("DropOffCharge"))
            //        ModelState["DropOffCharge"].Errors.Clear();

            //    if(model.Surcharge ==0)
            //    {
            //        ModelState.AddModelError("Surcharge", "Invalid Surcharge");
            //    }
            //}

            //model.IsAllPlot = model.AriaPointId == null ? 1 : model.IsAllPlot;
            model.IsAllPlot = (model.AreaPointId == null && model.IsAllPlot == 1) ? 1 : model.IsAllPlot;
            model.IsBothAreapointApplied = (model.FixedPriceId != null && model.IsAllPlot == 3);

            if (model.IsAllPlot == 1)
            {
                if (ModelState.ContainsKey("DropOffCharge"))
                    ModelState["DropOffCharge"].Errors.Clear();

                if (model.Surcharge == 0)
                {
                    ModelState.AddModelError("Surcharge", "Invalid Surcharge");
                }
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            rexSpecialOccasion.SaveSpecialOccasion(model);
            return View("SpecialOccasionView");
        }

        public ActionResult EditSpecialOccasionView(long id)
        {
            var model = rexSpecialOccasion.GetCurrentSpecialOccasion(id);
            model.OccasionDataRange = model.FromDate + "-" + model.ToDate;
             
            return View(model);
        }

        [HttpPost]
       public ActionResult EditSpecialOccasionView(SpecialOccasionViewModel model) 
       {
            //model.IsAllPlot = model.AriaPointId == null ? true : model.IsAllPlot;
            //if (model.IsAllPlot)
            //{
            //    if (ModelState.ContainsKey("DropOffCharge"))
            //        ModelState["DropOffCharge"].Errors.Clear();

            //    if (model.Surcharge == 0)
            //    {
            //        ModelState.AddModelError("Surcharge", "Invalid Surcharge");
            //    }
            //}

            model.IsAllPlot = (model.AreaPointId == null && model.IsAllPlot == 1) ? 1 : model.IsAllPlot;
            //model.IsBothAreapointApplied = (model.IsAllPlot == 2);
            model.IsBothAreapointApplied = (model.FixedPriceId != null && model.IsAllPlot == 3);

            if (model.IsAllPlot == 1)
            {
                if (ModelState.ContainsKey("DropOffCharge"))
                    ModelState["DropOffCharge"].Errors.Clear();

                if (model.Surcharge == 0)
                {
                    ModelState.AddModelError("Surcharge", "Invalid Surcharge");
                }
            }            

            if (!ModelState.IsValid)
            {
                return View(model);
            }
              rexSpecialOccasion.SaveSpecialOccasion(model);
            return View("SpecialOccasionView");
        }
    }
}

SwaranAdmin/SwaranAdmin_New/Views/SpecialOccasion/AddSpecialOccasionView_old.cshtml
@model SwaranAdmin_New.Models.PriceCalculation.SpecialOccasionViewModel

@{
    ViewBag.Title = "AddSpecialOccasionView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add New Special Occasion</h2>
<hr/>
<div class="col-md-12">
    <div class="col-md-6">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.ToDate)
            @Html.HiddenFor(model => model.FromDate)
            @Html.HiddenFor(model => model.CustomerRateId)
            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.Title, new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Title,new {@class = "form-control", @autocomplete = "off", @placeholder = "" })
                        @Html.ValidationMessageFor(model => model.Title, "", new {@class = "text-danger"})
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.RateName, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        <select class="form-control" id="rate">
                            <option selected="selected">Select</option>
                        </select>
                    </div>
                </div> 
 
                <div class="form-group">
                    @Html.LabelFor(model => model.RateFormula, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="row">
                        <div class="col-md-3">
                            @Html.TextBoxFor(model => model.RateName, new { @class = "form-control",@readonly= "readonly" } )
                        </div>
                        <div class="col-md-6">
                            @Html.TextBoxFor(model => model.RateFormula,   new { @class = "form-control", @autocomplete = "off", @placeholder = "" } )
                            @Html.ValidationMessageFor(model => model.RateFormula, "", new { @class = "text-danger" })
                        </div>
                    </div>
                  
                </div>

               
                <div class="form-group">
                    @Html.Label("Date Range", new { @class = "control-label col-md-2" })
                    <div class="input-group col-md-10">
                        <div class="input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </div>
                        @*<input type="text" id="reservationtime" class="form-control pull-right">*@

                        @Html.TextBoxFor(model => model.OccasionDataRange, new { @class = "form-control pull-right",@id= "reservationtime", @autocomplete = "off", @placeholder = "" })
                        @Html.ValidationMessageFor(model => model.OccasionDataRange, "", new { @class = "text-danger" })
                    </div>
                </div>

                
                <div class="form-group">
                    @Html.LabelFor(model => model.Surcharge, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Surcharge,   new { @class = "form-control", @autocomplete = "off", @placeholder = "" } )
                        @Html.ValidationMessageFor(model => model.Surcharge, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Comments,   new { @class = "form-control",@autocomplete = "off", @placeholder = "" } )
                        @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
                    </div>
                </div>

              

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>
 

  

@section scripts
{
    <script type="text/javascript">
        $(document).ready(function() {
            $('#reservationtime').daterangepicker(
            {
                autoApply: true,
                timePicker: true,
                timePicker24Hour: true,
                useCurrent: false, 
                timePickerIncrement: 15,
                locale: {
                    cancelLabel: 'Clear',
                    format: 'DD/MM/YYYY hh:mm A'
                }
            },function(start, end, label) {
               // $(this)[0].element.change(); 
                $("#FromDate").val(start.format('DD/MM/YYYY HH:mm'));
                $("#ToDate").val(end.format('DD/MM/YYYY HH:mm'));
               
                }

            );
            $('#reservationtime').val("");
            $.ajax({
                type: 'GET',
                url: '/api/pointofinterest/allcustomerrates',
                success: function(data) {
                    
                    for (var i = 0; i < data.length; i++) {
                        var opt = new Option(data[i].rateName);
                       // $("#rate").append(opt);
                        $("#rate").append(
                                $('<option/>', {
                                    value: data[i].rateId,
                                    text: data[i].rateName
                                }));
                    }
                }
            });

            $("#rate").on('change', function() {
                $("#CustomerRateId").val(this.value);
                $("#RateName").val($(this).find("option:selected").text());
            });
        });

    </script>
}

SwaranAdmin/SwaranAdmin_New/Views/SpecialOccasion/SpecialOccasionView.cshtml
<div class="box box-default box-solid">
    <div id="overLay" style="display: none">
        <i class="fa fa-refresh fa-spin"></i>
    </div>
    <div class="box-body">
        <h4>Special Occasion Rate Setup </h4>
        <hr />

        <input type="hidden" name="Ordercode" value="Norway">
        <div class="col-md-12" style="margin-bottom: 25px">
            <div class="col-md-4">
                 @Html.ActionLink("Add Special Occasion", "AddSpecialOccasionView", "SpecialOccasion",new { @class= "btn bg-maroon btn-flat margin" })
            </div>
        </div>

        <div class="col-md-12">
            <div class="box col-md-12">

                <table id="Occasions-grid" style="color: #000000" class="table table-bordered table-striped dataTable">
                    @*class="table table-bordered table-striped dataTable">*@
                    <thead>
                        <tr> 
                            <th>Title</th> 
                            <th>RateFormula</th>
                            <th>FromDate</th>
                            <th>ToDate</th>
                            <th>Surcharge</th>
                            <th>All UK</th>
                            <th>D/off_Chg</th>
                            <th>Comments</th>
                            <th></th>
                        </tr>
                    </thead>
                </table>

            </div>
        </div>


    </div>
</div>
@section scripts
{
    <script type="text/javascript">

                $(document).ready(function () {
                   
                   
                    var Table = $("#Occasions-grid").DataTable({
                        "oSearch": { "bSmart": false },
                        pageLength: 10,
                        "paging": true,
                        "ordering": true,
                        "info": true,
                        "filter": true,
                        aaSorting: [],
                        data: [],
                        columns: [ 
                            {
                                data: "title",
                                "width": "8%"
                            },
                            
                            {
                                data: "rateFormula",
                                "width": "10%"
                            },
                            {
                                data: "fromDate",
                                "width": "8%"
                            },
                             {
                                 data: "toDate",
                                 "width": "8%"
                             },{
                                 data: "surcharge",
                                 "width": "5%"
                             },
                              {
                                  data: "isAllPlot",
                                  "width": "5%"
                              },
                             {
                                 data: "dropOffCharge",
                                 "width": "5%"
                             },
                             
                            {
                                data: "comments", 
                            },
                            {
                                data: "occasionsId",
                                "width": "5%",
                                render: function (data, type, row) {

                                    return "<a href='/SpecialOccasion/EditSpecialOccasionView?id=" + data + "' class='btn btn-block btn-danger' > Edit </a>";
                                }
                            }

                             
                        ]

                    });


           

                    $("#overLay").show();
                    $("#overLay").addClass("overlay");
                    $.ajax({
                        url: "/api/pointofinterest/specialoccasion",
                        method: "GET",
                        success: function (data) {
                            $("#overLay").removeClass("overlay");
                            $("#overLay").hide();

                            Table.clear().draw();
                            Table.rows.add(data).draw();


                        },
                        error: function (data) {
                            $("#overLay").removeClass("overlay");
                            $("#overLay").hide();
                        }
                    });

                    $("#searchBtn").click(function () {

                        var bookingnumber = $("input[name='BookingNumber']").val();

                        $("#overLay").show();
                        $("#overLay").addClass("overlay");
                        $.ajax({
                            url: "/api/member/getrepaymentgrid?bookingnumber=" + bookingnumber,
                            method: "GET",
                            success: function (data) {
                                $("#overLay").removeClass("overlay");
                                $("#overLay").hide();
                                debugger;
                                if (data == null || data.length <= 0) {
                                    alert("Booking number not found");
                                    $("#refound-All").hide();
                                    return false;
                                }
                                Table.clear().draw();
                                Table.rows.add(data).draw();
                                if (  data[0].bookingToken == null) {
                                    $("#refound-All").hide();
                                } else {
                                    $("#refound-All").show();
                                }
                                $("#newLink").attr("href", "/WorldPayPayment/PayWorldpayOnline?tokent=" + data[0].bookingToken);

                            },
                            error: function (data) {
                            $("#overLay").removeClass("overlay");
                            $("#overLay").hide();
                        }
                        });
                    });


                    $(".jqueryui-marker-datepicker").datepicker(
                        {
                            minDate: 0,
                            dateFormat: "dd/mm/yy"
                        }).css("display", "inline-block")
                        .next("button").button(
                        {
                            icons: { primary: "ui-icon-calendar" },
                            lable: "Select a date",
                            text: false
                        });


                });
    </script>
}